### ISSUE TITLE
Capella5.0 not work on ubuntu18.04

### ISSUE THREAD

**Issue by SummerOf15** [eclipse/capella#2031]
I install the capella 5.0 (capella-5.0.0.202101071610-linux-gtk-x86_64) in ubuntu 18.04. I can open the software but when I click create a new OEBD, it fails to open a new window. I read the log file, here is the error.

!ENTRY org.eclipse.ui 4 0 2021-01-12 10:41:25.316
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException

**Comment by pdulth** [comment]
Hi,

Can you provide the Error Log,
Window > Show View > Error Log
In the opened view, Export Log

Thanks,

**Comment by SummerOf15** [comment]
There is no such an option. But I find the log under directory.
!ENTRY org.eclipse.ui 4 0 2021-01-12 10:55:56.294
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at org.polarsys.capella.core.sirius.ui.actions.NewRepresentationAction.<init>(NewRepresentationAction.java:70)
	at org.polarsys.capella.core.explorer.activity.ui.hyperlinkadapter.AbstractCapellaNewDiagramHyperlinkAdapter.initNewRepresentationAction(AbstractCapellaNewDiagramHyperlinkAdapter.java:79)
	at org.polarsys.capella.core.explorer.activity.ui.hyperlinkadapter.AbstractCapellaNewDiagramHyperlinkAdapter.createDiagram(AbstractCapellaNewDiagramHyperlinkAdapter.java:66)
	at org.eclipse.amalgam.explorer.activity.ui.api.hyperlinkadapter.AbstractNewDiagramHyperlinkAdapter.linkPressed(AbstractNewDiagramHyperlinkAdapter.java:89)
	at org.polarsys.capella.core.explorer.activity.ui.hyperlinkadapter.AbstractCapellaNewDiagramHyperlinkAdapter.linkActivated(AbstractCapellaNewDiagramHyperlinkAdapter.java:56)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleActivate(AbstractHyperlink.java:215)
	at org.eclipse.ui.forms.widgets.ImageHyperlink.handleActivate(ImageHyperlink.java:212)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleMouseUp(AbstractHyperlink.java:309)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.lambda$3(AbstractHyperlink.java:117)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5685)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4953)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4446)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.polarsys.capella.core.platform.sirius.ui.app.CapellaApplication.start(CapellaApplication.java:117)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)

**Comment by pdulth** [comment]
Hi, 

I reproduced your issue, 

On the new project creation wizard, the model has been created without enabling the Operational Analysis in the "Viewpoint selection", like below.
![2031](https://user-images.githubusercontent.com/34767327/104301611-27089b80-54c8-11eb-99f0-79dd8e37ad9e.gif)

You can create a model by clicking on "Finish" on the first pane of the wizard :
![2031-2](https://user-images.githubusercontent.com/34767327/104301616-27a13200-54c8-11eb-8745-f9e521fcd472.gif)


Its possible to enable "viewpoints" afterwards. On aird in project explorer view, rightclick, Viewpoints selection.

**Comment by SummerOf15** [comment]
Hello,

It works. Thank you so much.
