### ISSUE TITLE
PhysicalComponentNatureGroup.setEnabled should check if the button widget is not disposed before modifications

### ISSUE THREAD

**Issue by SteveMonnier** [eclipse/capella#2070]
In the method org.polarsys.capella.core.data.pa.properties.fields.PhysicalComponentNatureGroup.setEnabled(boolean) a button foreground color is modified. However, the method should check that the button is not disposed as this happens from time to time with Team for Capella.
For the moment, no scenario has been found that could always reproduce the issue.
Here is a stack trace of the issue during saving:

>org.eclipse.swt.SWTException: Widget is disposed
>	at org.eclipse.swt.SWT.error(SWT.java:4699)
>	at org.eclipse.swt.SWT.error(SWT.java:4614)
>	at org.eclipse.swt.SWT.error(SWT.java:4585)
>	at org.eclipse.swt.widgets.Widget.error(Widget.java:451)
>	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:350)
>	at org.eclipse.swt.widgets.Control.setForeground(Control.java:3499)
>	at org.polarsys.capella.core.data.pa.properties.fields.PhysicalComponentNatureGroup.setEnabled(PhysicalComponentNatureGroup.java:83)
>	at org.polarsys.capella.core.ui.properties.sections.AbstractSection.setEnabled(AbstractSection.java:348)
>	at com.thalesgroup.mde.melody.collab.ui.lock.listeners.CDOReadOnlySectionHandler$EnableJob.doIT(CDOReadOnlySectionHandler.java:60)
>	at com.thalesgroup.mde.melody.collab.ui.lock.listeners.AbstractRefreshUiJob.runInUIThread(AbstractRefreshUiJob.java:41)
>	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
>	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)

**Comment by michelbispo** [comment]
Please, can you give more information, Capella version number for instance
