### ISSUE TITLE
Updating a comparison may raise an IllegalStateException

### ISSUE THREAD

**Issue by oconstant** [eclipse/capella#2164]
Reproduction steps with Capella 5.0.0:
- Start Capella.
- Create two fresh Capella models.
- Compare them (.aird or .melodymodeller) using default settings.
- In the Comparison editor, select Update... and select configuration "Transfer of elements between models created independently".
- Click finish: the editor does not update and an error is eventually shown, see below.

java.lang.IllegalStateException: Cannot modify resource set without a write transaction
	at org.eclipse.emf.transaction.impl.TransactionChangeRecorder.assertWriting(TransactionChangeRecorder.java:349)
	at org.eclipse.emf.transaction.impl.TransactionChangeRecorder.appendNotification(TransactionChangeRecorder.java:303)
	at org.eclipse.emf.transaction.impl.TransactionChangeRecorder.processObjectNotification(TransactionChangeRecorder.java:285)
	at org.eclipse.emf.transaction.impl.TransactionChangeRecorder.notifyChanged(TransactionChangeRecorder.java:241)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.emf.diffmerge.generic.gdiffdata.impl.GMatchImpl.setTargetOwnershipDifference(GMatchImpl.java:395)
	at org.eclipse.emf.diffmerge.generic.gdiffdata.impl.GMatchImpl.addOwnershipDifference(GMatchImpl.java:567)
	at org.eclipse.emf.diffmerge.generic.gdiffdata.impl.GMatchImpl.addRelatedDifference(GMatchImpl.java:643)
	at org.eclipse.emf.diffmerge.generic.gdiffdata.impl.GReferenceValuePresenceImpl.<init>(GReferenceValuePresenceImpl.java:86)
	at org.eclipse.emf.diffmerge.diffdata.impl.EReferenceValuePresenceImpl.<init>(EReferenceValuePresenceImpl.java:88)
	at org.eclipse.emf.diffmerge.diffdata.impl.EComparisonImpl.newReferenceValuePresence(EComparisonImpl.java:164)
	at org.eclipse.emf.diffmerge.diffdata.impl.EComparisonImpl.newReferenceValuePresence(EComparisonImpl.java:1)
	at org.eclipse.emf.diffmerge.generic.impl.helpers.DiffOperation.createReferenceValueDifference(DiffOperation.java:194)
	at org.eclipse.emf.diffmerge.generic.impl.helpers.DiffOperation.detectReferenceDifferences(DiffOperation.java:469)
	at org.eclipse.emf.diffmerge.generic.impl.helpers.DiffOperation.detectAllReferenceDifferences(DiffOperation.java:267)
	at org.eclipse.emf.diffmerge.generic.impl.helpers.DiffOperation.detectContentDifferences(DiffOperation.java:364)
	at org.eclipse.emf.diffmerge.generic.impl.helpers.DiffOperation.createTechnicalDifferences(DiffOperation.java:212)
	at org.eclipse.emf.diffmerge.generic.impl.helpers.DiffOperation.createDifferences(DiffOperation.java:158)
	at org.eclipse.emf.diffmerge.generic.impl.helpers.DiffOperation.run(DiffOperation.java:673)
	at org.eclipse.emf.diffmerge.generic.impl.helpers.AbstractExpensiveOperation.run(AbstractExpensiveOperation.java:66)
	at org.eclipse.emf.diffmerge.generic.gdiffdata.impl.GComparisonImpl.computeDiff(GComparisonImpl.java:634)
	at org.eclipse.emf.diffmerge.generic.gdiffdata.impl.GComparisonImpl.compute(GComparisonImpl.java:601)
	at org.eclipse.emf.diffmerge.ui.viewers.ComparisonViewer$RestartJob.restart(ComparisonViewer.java:3439)
	at org.eclipse.emf.diffmerge.ui.viewers.ComparisonViewer$RestartJob.run(ComparisonViewer.java:3396)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by oconstant** [comment]
This regression occurs in Capella 5.0.0, not in 1.4.2.

**Comment by oconstant** [comment]
I tested a fix that seems to work, but I then run into the following:

java.lang.NullPointerException
	at org.eclipse.emf.diffmerge.generic.gdiffdata.impl.GElementRelativePresenceImpl.getPresenceScope(GElementRelativePresenceImpl.java:309)
	at org.eclipse.emf.diffmerge.generic.gdiffdata.impl.GReferenceValuePresenceImpl.isContainment(GReferenceValuePresenceImpl.java:296)
	at org.eclipse.emf.diffmerge.generic.gdiffdata.impl.GReferenceValuePresenceImpl.isOwnership(GReferenceValuePresenceImpl.java:341)
	at org.eclipse.emf.diffmerge.generic.gdiffdata.impl.GReferenceValuePresenceImpl.isUnrelatedToContainmentTree(GReferenceValuePresenceImpl.java:359)
	at org.eclipse.emf.diffmerge.ui.viewers.CategoryManager.representAsModificationDifference(CategoryManager.java:882)
	at org.eclipse.emf.diffmerge.ui.viewers.CategoryManager.representAsModification(CategoryManager.java:866)
	at org.eclipse.emf.diffmerge.ui.viewers.ComparisonViewer.refreshTools(ComparisonViewer.java:2771)
	at org.eclipse.emf.diffmerge.ui.viewers.ComparisonViewer$72.selectionChanged(ComparisonViewer.java:3070)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:148)
	at org.eclipse.emf.diffmerge.ui.viewers.ComparisonViewer.setSelection(ComparisonViewer.java:2925)
	at org.eclipse.emf.diffmerge.ui.viewers.ComparisonViewer$55.widgetSelected(ComparisonViewer.java:1717)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4213)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4030)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3630)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.polarsys.capella.studio.product.Application.start(Application.java:127)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)

**Comment by oconstant** [comment]
It makes sense. I'm working on a fix for that too.

**Comment by oconstant** [comment]
Cf. https://bugs.eclipse.org/bugs/show_bug.cgi?id=572779 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=572780.
