### ISSUE TITLE
NPE on closing Richtext "documentation" on Activity Explorer

### ISSUE THREAD

**Issue by arnauddieumegard** [eclipse/capella#2330]
Closing the Richtext "documentation" editor by closing the Activity Explorer raise an NPE on Capella 6.0.0.

Steps to reproduce:
- Open IFE session
- Navigate to Activity Explorer
- Open Documentation tab
- Close Activity Explorer editor
- Witness error:

```
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
	at java.base/java.util.regex.Matcher.reset(Unknown Source)
	at java.base/java.util.regex.Matcher.<init>(Unknown Source)
	at java.base/java.util.regex.Pattern.matcher(Unknown Source)
	at org.eclipse.sirius.business.internal.image.ImageManagerForWorkspaceResource.convertToOriginalPathFromPathUsedForHtml(ImageManagerForWorkspaceResource.java:167)
	at org.polarsys.kitalpha.richtext.common.impl.AbstractMDERichTextWidget.saveContent(AbstractMDERichTextWidget.java:108)
	at org.polarsys.kitalpha.richtext.common.impl.AbstractMDERichTextWidget.dispose(AbstractMDERichTextWidget.java:196)
	at org.polarsys.kitalpha.richtext.nebula.widget.MDENebulaBasedRichTextWidgetImpl.dispose(MDENebulaBasedRichTextWidgetImpl.java:403)
	at org.polarsys.capella.core.explorer.activity.ui.richtext.page.CapellaDocumentationActivityExplorerPage.dispose(CapellaDocumentationActivityExplorerPage.java:77)
	at org.eclipse.ui.forms.editor.FormEditor.dispose(FormEditor.java:410)
	at org.eclipse.ui.forms.editor.SharedHeaderFormEditor.dispose(SharedHeaderFormEditor.java:163)
	at org.eclipse.amalgam.explorer.activity.ui.api.editor.ActivityExplorerEditor.dispose(ActivityExplorerEditor.java:415)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.invalidate(CompatibilityPart.java:264)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.destroy(CompatibilityPart.java:421)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```

During reproduction attempts some `java.lang.NullPointerException` with empty stack also occured. But I cannot reproduce them.

I did **not** witness the same error on Capella 5.2.0 using same scenario.
I did **not** witness the same error on Kitalpha using same scenario.

**Comment by arnauddieumegard** [comment]
Fixed in https://github.com/eclipse/kitalpha/commit/cc1e4ace004209e730f4eda3b715603ce5972046
