### ISSUE TITLE
Creating diagrams stopped working on fragmented models [Linux 6.X.0]

### ISSUE THREAD

**Issue by MoritzWeber0** [eclipse/capella#2656]
With Capella versions 6.0.0 and 6.1.0, no diagrams can be created anymore on fragmented models with the Linux package. 
Steps to reproduce: 
- Create an empty model
- Fragment a layer, e.g. Operational Analysis
- Add a new diagram

Nothing happens and the error message in the error log is: "Unhandled event loop exception" with the following stack trace:
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Shell.getDisplay()" because the return value of "org.eclipse.ui.dialogs.FilteredItemsSelectionDialog.access$0(org.eclipse.ui.dialogs.FilteredItemsSelectionDialog)" is null
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$RefreshProgressMessageJob.<init>(FilteredItemsSelectionDialog.java:1329)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog.<init>(FilteredItemsSelectionDialog.java:202)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog.<init>(FilteredItemsSelectionDialog.java:264)
	at org.eclipse.sirius.ui.tools.api.dialogs.AnalysisSelectorFilteredItemsSelectionDialog.<init>(AnalysisSelectorFilteredItemsSelectionDialog.java:101)
	at org.polarsys.capella.core.sirius.ui.danalysis.CapellaAnalysisSelector.createAnalysisSelectorDialog(CapellaAnalysisSelector.java:46)
	at org.eclipse.sirius.ui.business.api.session.analysis.SmartDialogAnalysisSelector$1.getResultFromDialog(SmartDialogAnalysisSelector.java:87)
	at org.eclipse.sirius.ui.business.api.session.analysis.SmartDialogAnalysisSelector$1.run(SmartDialogAnalysisSelector.java:80)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5996)
	at org.eclipse.sirius.common.ui.tools.api.util.EclipseUIUtil.displaySyncExec(EclipseUIUtil.java:337)
	at org.eclipse.sirius.ui.business.api.session.analysis.SmartDialogAnalysisSelector.selectSmartlyAnalysis(SmartDialogAnalysisSelector.java:109)
	at org.polarsys.capella.core.sirius.ui.danalysis.CapellaAnalysisSelector.selectSmartlyAnalysisForAddedRepresentation(CapellaAnalysisSelector.java:35)
	at org.eclipse.sirius.business.api.session.danalysis.DAnalysisSessionHelper.selectAnalysis(DAnalysisSessionHelper.java:92)
	at org.eclipse.sirius.business.api.session.danalysis.DAnalysisSessionHelper.findContainerForAddedRepresentation(DAnalysisSessionHelper.java:192)
	at org.eclipse.sirius.business.internal.query.DRepresentationDescriptorInternalHelper.createDRepresentationDescriptor(DRepresentationDescriptorInternalHelper.java:112)
	at org.eclipse.sirius.business.api.dialect.AbstractRepresentationDialectServices.createRepresentation(AbstractRepresentationDialectServices.java:233)
	at org.eclipse.sirius.business.internal.dialect.DialectManagerImpl.createRepresentation(DialectManagerImpl.java:144)
	at org.polarsys.capella.core.sirius.ui.actions.NewRepresentationAction$NewRepresentationCommand.run(NewRepresentationAction.java:229)
	at org.polarsys.capella.common.ef.ExecutionManager$2.doExecute(ExecutionManager.java:129)
	at org.eclipse.emf.transaction.RecordingCommand.execute(RecordingCommand.java:135)
	at org.eclipse.emf.workspace.EMFCommandOperation.doExecute(EMFCommandOperation.java:119)
	at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:150)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:496)
	at org.polarsys.capella.common.ef.internal.command.WorkspaceCommandStackImpl.doExecute(WorkspaceCommandStackImpl.java:150)
	at org.polarsys.capella.common.platform.sirius.ted.SemanticEditingDomainFactory$SemanticCommandStack.doExecute(SemanticEditingDomainFactory.java:277)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:165)
	at org.polarsys.capella.common.ef.ExecutionManager.executeReadWriteCommand(ExecutionManager.java:93)
	at org.polarsys.capella.common.ef.ExecutionManager.execute(ExecutionManager.java:68)
	at org.polarsys.capella.core.sirius.ui.actions.NewRepresentationAction.run(NewRepresentationAction.java:165)
	at org.eclipse.ui.actions.BaseSelectionListenerAction.runWithEvent(BaseSelectionListenerAction.java:171)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5879)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5121)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4599)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.polarsys.capella.core.platform.sirius.ui.app.CapellaApplication.start(CapellaApplication.java:118)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1435)

```

We reproduced the issue on multiple Linux devices, also with fresh workspaces. We could not reproduce it with the macOS archive, everything works fine there.

With Capella version 5.2.0, the feature works as expected (also for Linux packages), so the bug has been introduced in version 6.0.0. This is the dialog which appears for version 5.2.0, but it doesn't for 6.X.0:
![2023-06-07_11-40](https://github.com/eclipse/capella/assets/23395732/9433f8e7-0380-4ee0-b083-7d4d753dc095)

Interesting enough, it works for TeamForCapella models. For TeamForCapella models, the dialog shows up:
![image](https://github.com/eclipse/capella/assets/23395732/05ed01c1-267f-4e4f-bfc5-735c54f727e8)

This is an important feature for users within our organisation and has worked before. Is there a chance to provide a patch in the short-term? Thanks for a reply in advance.

**Comment by mPorhel** [comment]
Hi, 

The issue comes from 

`org.polarsys.capella.core.sirius.ui.danalysis.CapellaAnalysisSelector.createAnalysisSelectorDialog(Shell, DAnalysis, Collection<DAnalysis>, List<DAnalysis>, DRepresentation)`

which does not reuse the shell from its parameters but call Display.getDefault().getActiveShell() which returns null in some cases  in Linux.

It was corrected in Eclipse Sirius 7.0.1 via  https://bugs.eclipse.org/bugs/show_bug.cgi?id=579280






le shell passé en paramètre n'est pas réutilisé
