### ISSUE TITLE
REC/REPL seems to be broken 

### ISSUE THREAD

**Issue by ewuerger** [eclipse/capella#2660]
When I create a REC of a PhysicalComponent the Capella application a REC Catalog will be created with the Rec object. But now If I want to make a REPL on a new created PhysicalComponent I canchoose the REC and the REC Catalog, but the window won't allow for `Ok`.
![image](https://github.com/eclipse/capella/assets/50786483/d4cf7380-4a36-45c1-9a44-685239c28aaf)

Now Capella behaves weirdly and after closing?opening the model again I receive errors:
![image](https://github.com/eclipse/capella/assets/50786483/27ac0687-e853-40ef-a4cd-3f1630d6c187)

Only closing and opening Capella will fix this. Then the instantion window looks fine:
![image](https://github.com/eclipse/capella/assets/50786483/c1292a3d-2418-4faf-9837-4b4e5ed4e3df)

But clicking on `Ok` won't create the REPL graphically. It is there in the browser.
![image](https://github.com/eclipse/capella/assets/50786483/117c3933-f4b7-4a47-a32d-2c61a8534e21)

The new Component still looks the same in the diagram.
![image](https://github.com/eclipse/capella/assets/50786483/90735a5f-a2be-4c46-a3c5-a25b15a67348)

The application is again malfunctioning and spawning the same errors as before. Our users would like to use this feature but can't in it's current state.

Is there a chance to provide a patch in the short-term? Thanks for a reply in advance.

**Comment by etraisnel2** [comment]
Hello,

What version of Capella are you working with ?

B.R 

Erwann

**Comment by ewuerger** [comment]
Hi,

this happened while using Capella 6.0.0 (6.0.0.202209090800).

**Comment by etraisnel2** [comment]
I tried to reproduce it on a Capella 6.0.0 on windows, but it works for me ...
It feels like your Capella installation might be broken
I would advise to try on a fresh Capella 6.0.0 install.
If you can reproduce it again, could you please provide the stack trace from the "Unhandled Loop Exception" errors ?

B.R

**Comment by OhItsHarry** [comment]
Hi,

I have a similar issue, but for me it was not possible to restore it by re-opening Capella nor by a fresh install. I cannot create Physical Architecture Diagrams or Physical Component Breakdown Diagrams, both give me unhandled event loop exception in one of my projects. It does not occure in another project, which seems strange, since I expected it to be not an issue on project site.

I am using Capella 6.1.0 on Windows 10.

Thanks and Kind Regards

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.sirius.viewpoint.description.RepresentationDescription.getName()" because "description" is null
	at org.polarsys.capella.core.sirius.ui.actions.NewRepresentationAction.<init>(NewRepresentationAction.java:59)
	at org.polarsys.capella.core.explorer.activity.ui.hyperlinkadapter.AbstractCapellaNewDiagramHyperlinkAdapter.initNewRepresentationAction(AbstractCapellaNewDiagramHyperlinkAdapter.java:84)
	at org.polarsys.capella.core.explorer.activity.ui.hyperlinkadapter.AbstractCapellaNewDiagramHyperlinkAdapter.createDiagram(AbstractCapellaNewDiagramHyperlinkAdapter.java:70)
	at org.eclipse.amalgam.explorer.activity.ui.api.hyperlinkadapter.AbstractNewDiagramHyperlinkAdapter.linkPressed(AbstractNewDiagramHyperlinkAdapter.java:89)
	at org.polarsys.capella.core.explorer.activity.ui.hyperlinkadapter.AbstractCapellaNewDiagramHyperlinkAdapter.linkActivated(AbstractCapellaNewDiagramHyperlinkAdapter.java:60)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleActivate(AbstractHyperlink.java:215)
	at org.eclipse.ui.forms.widgets.ImageHyperlink.handleActivate(ImageHyperlink.java:212)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleMouseUp(AbstractHyperlink.java:309)
	at org.eclipse.ui.forms.widgets.AbstractHyperlink.lambda$3(AbstractHyperlink.java:117)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.polarsys.capella.core.platform.sirius.ui.app.CapellaApplication.start(CapellaApplication.java:118)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
```

**Comment by OhItsHarry** [comment]
Hi,

My colleague and I found a workaround by using the Sirius Model Explorer. The right click menu of the Physical Architecture in the Project Explorer also does not offer the possibility to add the PAB, but in the Sirius Model Explorer it is possible to add it on Physical System -> New Representation -> Other. After doing this, the diagram is added and it is also possible to add all other diagrams, which didn't work before. All menus behave as normal after doing this.

Kind regards

**Comment by kacper-ka** [comment]
@ewuerger did fresh install resolve the issue, as @etraisnel2 suggested? I am facing the exact same symptoms, both running _Capella_ locally and in a container (from @dsd-dbs/capella-dockerimages)

**Comment by ewuerger** [comment]
I will check on thursday. Thank you for the update.

**Comment by kacper-ka** [comment]
I have also verified that I can reliably reproduce the issue with a fresh workspace and a new project.

**Comment by ewuerger** [comment]
> @ewuerger did fresh install resolve the issue, as @etraisnel2 suggested? I am facing the exact same symptoms, both running _Capella_ locally and in a container (from @dsd-dbs/capella-dockerimages)

I am experiencing the same symptoms as initially described, both when running **Capella** locally and in a container (from `@dsd-dbs/capella-dockerimages`).

## Versions Tested
- **v7.0.0-202407091438**: Latest stable version (fresh download on Ubuntu 22.04)
- **v6.1.0**: Container version (from `@dsd-dbs/capella-dockerimages`)

The issue persists across both scenarios.

## Steps to Reproduce

### 1. Working Scenario
Using `Instantiate RPL from REC` on a `PhysicalComponent` marked with `[REC]` works as expected:
- A replicate is created and marked with `[RPL]`.
- The corresponding trace is added to the REC Catalog.
- Deleting the replicate requires manual removal from the REC Catalog (tedious but expected behavior).

### 2. Problematic Scenario
Using `Instantiate RPL from REC` on an **existing** `PhysicalComponent` causes:
- **UI freeze**.
- Multiple **Unhandled event loop exceptions** caused by a **NullPointerException** (similar to the stack trace shared by `@OhItsHarry`).
- Requires a restart to regain functionality.

### 3. New Observations (v7.0.0)
After a restart, attempting `Instantiate RPL from REC` again on the same `PhysicalComponent`:
- The Catalog option is prefilled.
- Selecting the REC and confirming (`OK`) creates a replica as a child component.
- However, this does not align with the intended use case of applying a REC to an existing component while retaining relationships and properties but overwriting content based on the REC. I guess this isn't covered at all by Capella yet.

## Expected Behavior
The operation should not crash Capella.

### New feature idea
An operation for applying a REC to an existing component retaining relationships and properties, except the ones defined in the REC.

## Stack Trace for 2.
```java
java.lang.NullPointerException: Cannot read field "alpha" because "gdkRGBA" is null
	at org.eclipse.swt.graphics.Color.gtk_new(Color.java:480)
	at org.eclipse.swt.graphics.GC.getBackground(GC.java:2009)
	at org.eclipse.ui.internal.forms.widgets.FormImages$ComplexImageDescriptor.drawTextGradient(FormImages.java:198)
	at org.eclipse.ui.internal.forms.widgets.FormImages$ComplexImageDescriptor.createImage(FormImages.java:191)
	at org.eclipse.jface.resource.ImageDescriptor.createResource(ImageDescriptor.java:227)
	at org.eclipse.jface.resource.DeviceResourceManager.allocate(DeviceResourceManager.java:55)
	at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:88)
	at org.eclipse.jface.resource.LocalResourceManager.allocate(LocalResourceManager.java:72)
	at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:88)
	at org.eclipse.jface.resource.ResourceManager.createImage(ResourceManager.java:175)
	at org.eclipse.ui.internal.forms.widgets.FormImages.getGradient(FormImages.java:351)
	at org.eclipse.ui.internal.forms.widgets.FormImages.getGradient(FormImages.java:346)
	at org.eclipse.ui.internal.forms.widgets.FormHeading.updateGradientImage(FormHeading.java:902)
	at org.eclipse.ui.internal.forms.widgets.FormHeading.setTextBackground(FormHeading.java:752)
	at org.eclipse.ui.forms.widgets.Form.setTextBackground(Form.java:337)
	at org.eclipse.ui.forms.widgets.FormToolkit.decorateFormHeading(FormToolkit.java:732)
	at org.eclipse.amalgam.explorer.activity.ui.api.editor.pages.CommonActivityExplorerPage.createFormContent(CommonActivityExplorerPage.java:74)
	at org.eclipse.amalgam.explorer.activity.ui.api.editor.pages.OverviewActivityExplorerPage.createFormContent(OverviewActivityExplorerPage.java:139)
	at org.eclipse.ui.forms.editor.FormPage.lambda$0(FormPage.java:166)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.forms.editor.FormPage.createPartControl(FormPage.java:166)
	at org.eclipse.ui.forms.editor.FormEditor.pageChange(FormEditor.java:480)
	at org.eclipse.ui.part.MultiPageEditorPart.setActivePage(MultiPageEditorPart.java:1030)
	at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:612)
	at org.eclipse.ui.forms.editor.SharedHeaderFormEditor.createPages(SharedHeaderFormEditor.java:109)
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:333)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:96)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:999)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:964)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:140)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:405)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:332)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:999)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:765)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:730)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:714)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.lambda$0(PartServiceImpl.java:104)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5996)
	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:133)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:170)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:188)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:660)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:624)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:786)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:400)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1260)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3195)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$9(WorkbenchPage.java:3100)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3098)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3068)
	at org.polarsys.capella.core.sirius.ui.actions.OpenSessionAction$2.run(OpenSessionAction.java:283)
	at org.polarsys.capella.core.sirius.ui.actions.OpenSessionAction.openActivityExplorer(OpenSessionAction.java:299)
	at org.polarsys.capella.core.explorer.activity.ui.actions.OpenActivityExplorerAction.run(OpenActivityExplorerAction.java:61)
	at org.eclipse.ui.actions.BaseSelectionListenerAction.runWithEvent(BaseSelectionListenerAction.java:171)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5879)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5121)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4599)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.polarsys.capella.core.platform.sirius.ui.app.CapellaApplication.start(CapellaApplication.java:118)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1435)
...
```

## Additional Information
Workaround shared by @OhItsHarry

> Using the Sirius Model Explorer, it is possible to add representations (e.g., PAB) under Physical System -> New Representation -> Other. This restores functionality for adding diagrams and interacting with menus normally.

My Observations
- This workaround does not restore the Activity Explorer for me.
- However, manual modeling tasks like opening diagrams and changing properties work.

Hope this clarifies and helps to reproduce the issue. Happy new year!

**Comment by mateusfbsoares** [comment]
I'm having a similar problem on multiple 6.x and 7.x Capella Versions, running both on fedora natively on my machine and on ubuntu on a virtual machine: Any interaction with REC/RPL menu (opening the menu to create a REC, instanciate an RPL or update a RPL from REC) will trigger this bug, which makes capella all buggy, but the diagram seem to run fine. However it causes a lot of problems preventing normal use. See vídeo below of demonstration.

Does anyone have an idea for a solution? I'm days stuck in this...

[https://youtu.be/anB0WfH97Wo](https://youtu.be/anB0WfH97Wo)

**Comment by mPorhel** [comment]
Hi, 

I have provided a PR for Capella master branch which allows to avoid those issues on my side: #2947
