### ISSUE TITLE
Exception when using "delete" on representation categories

### ISSUE THREAD

**Issue by Kellindil** [eclipse/capella#2666]
In any project, select the "category" of a diagram within the "Representations per category" folder:

![image](https://github.com/eclipse/capella/assets/661592/c6d02c06-0296-47be-bfd2-fde295d3c17e)

Then hit the "delete" key (or right-click > Delete).

The following is thrown:

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.polarsys.capella.core.platform.sirius.ui.actions.CapellaDeleteAction.run(CapellaDeleteAction.java:123)
	at org.eclipse.ui.actions.BaseSelectionListenerAction.runWithEvent(BaseSelectionListenerAction.java:171)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.polarsys.capella.core.platform.sirius.ui.app.CapellaApplication.start(CapellaApplication.java:118)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1435)
Caused by: java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:445)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:468)
	at org.polarsys.capella.core.platform.sirius.ui.actions.CapellaDeleteAction.run(CapellaDeleteAction.java:120)
	... 30 more
Caused by: org.eclipse.core.runtime.AssertionFailedException: assertion failed: The Editing Domain must be not null and must be a Transactional one
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:113)
	at org.polarsys.capella.core.model.handler.command.DeleteCommand.<init>(DeleteCommand.java:58)
	at org.polarsys.capella.core.model.handler.command.DeleteStructureCommand.<init>(DeleteStructureCommand.java:34)
	at org.polarsys.capella.core.model.handler.command.PreDeleteStructureCommand.<init>(PreDeleteStructureCommand.java:43)
	at org.polarsys.capella.core.model.handler.command.BasicCapellaDeleteCommand.getAllElementsToDelete(BasicCapellaDeleteCommand.java:438)
	at org.polarsys.capella.core.model.handler.command.BasicCapellaDeleteCommand.getAllControlledElementsToDelete(BasicCapellaDeleteCommand.java:415)
	at org.polarsys.capella.core.model.handler.command.BasicCapellaDeleteCommand.execute(BasicCapellaDeleteCommand.java:173)
	at org.polarsys.capella.core.platform.sirius.ui.actions.CapellaDeleteAction$1.run(CapellaDeleteAction.java:115)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:436)
	... 33 more

**Comment by etraisnel2** [comment]
Hi ! 
I've taken a look at it.
The exception is thrown because there is no execution manager nor transactional editing domain.

The execution manager is deduced from TransactionHelper.getExecutionManager(selection)
on the actual selection, where any element that isn't an EObject is filtered out.

The item you tried to delete is a org.eclipse.sirius.ui.tools.internal.views.common.item.RepresentationDescriptionItemImpl
which isn't an EObject, hence resulting in an empty selection

A fix could be to handle these cases and to delete all the Representations contained inside of it
